x-build:
  &common-build
  context: .
  dockerfile: build/docker/DockerFile
  args:
    - tag=tcc

x-config:
  &common-config
  image: tcc
  stdin_open: true # interactive
  tty: true
  privileged: true

x-gpu:
  &x-gpu
  environment:
    - NVIDIA_DRIVER_CAPABILITIES=all
  # The following options represent '-gpus all' argument
  deploy: 
    resources:
      reservations:
        devices:
        - driver: nvidia
          count: 1
          capabilities: [gpu]

services:
  windows:
    # Build Options
    build:
      <<: *common-build
    <<: *common-config

    # Run Options
    container_name: tcc_windows
    environment:
      - DISPLAY=:0
      - WAYLAND_DISPLAY=wayland-0
      - XDG_RUNTIME_DIR=/mnt/wslg/runtime-dir
      - PULSE_SERVER=/mnt/wslg/PulseServer
    volumes:
      - /run/desktop/mnt/host/wslg/.X11-unix:/tmp/.X11-unix
      - /run/desktop/mnt/host/wslg:/mnt/wslg
      - .:/home/developer/project

  linux:
    # Build Options
    build:
      <<: *common-build
    <<: *common-config

    # Run Options
    container_name: tcc_linux
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/home/developer/project

