---
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

# - ros_topic_name: "/joint_states"
#   gz_topic_name: "/world/empty/model/joint_state"
#   ros_type_name: "sensor_msgs/msg/JointState"
#   gz_type_name: "gz.msgs.Model"
#   direction: GZ_TO_ROS

# - ros_topic_name: "/clock"
#   gz_topic_name: "/clock"
#   ros_type_name: "rosgraph_msgs/msg/Clock"
#   gz_type_name: "gz.msgs.Clock"
#   direction: GZ_TO_ROS